version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app/__init__.py
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=sqlite:///site.db
    volumes:
      - .:/app
